In [1]:
import numpy as np


In [2]:
points = []
true_w =np.array([1,2,3,4,5])
D = len(true_w)

for i in range (50000):
    x = np.random.randn(D)
    y = true_w.dot(x) + np.random.randn()
    points.append((x,y))
# points

In [4]:
points

[(array([ 0.409584  , -1.36739103, -0.44856706, -1.26576932, -1.0694873 ]),
  -13.632445155935875),
 (array([-0.95138433,  1.94514309, -0.38451503, -0.7867522 , -1.46719237]),
  -8.13736409159285),
 (array([-1.09412635, -1.89306738, -1.03659001,  1.20143352,  0.22838896]),
  -3.9269881459525378),
 (array([ 0.26724915,  0.19613304, -0.96593501, -0.74385734,  0.11479393]),
  -4.97374024900536),
 (array([-0.48279958, -0.58308315,  0.61644545,  0.0466425 ,  0.07007547]),
  0.3623699883434867),
 (array([-0.5579011 ,  1.22113953,  1.00095111,  0.24104165,  0.54636739]),
  7.782175768584895),
 (array([-0.05103088,  1.64459429, -1.11406536, -0.56110247,  0.38867808]),
  -0.3667829318573613),
 (array([-0.47331748, -1.21384984, -0.71614095,  0.37696219,  1.61144936]),
  3.3102949347495914),
 (array([-1.7457312 ,  0.50126463, -0.45914803,  1.57956413, -0.85795147]),
  0.7182685632364146),
 (array([-1.96999975,  1.25603856, -0.09571052, -0.96318031,  0.60968286]),
  0.34233667893449127),
 (array([

In [29]:
def Loss(w):
    return sum((w.dot(x)-y)**2 for x ,y in points)/len(points)

def dLoss(w):
    return sum(2*(w.dot(x)-y)*x for x,y in points ) /len(points)

def GradientDescent(Loss,dLoss,D):
    w = np.zeros(D)
    lr = 0.01
    
    for i in range(1000):
        loss = Loss(w)
        Gradient = dLoss(w)
        w = w -lr*Gradient
        print(f'Iterations {i}: w = {w},L(w) = {loss}')

GradientDescent(Loss,dLoss,D)


Iterations 0: w = [0.02382087 0.04554707 0.0535473  0.0835563  0.1055085 ],L(w) = 57.81004473429066
Iterations 1: w = [0.04708989 0.09007224 0.10616494 0.16533994 0.20878238],L(w) = 55.472414519627
Iterations 2: w = [0.06981973 0.13359843 0.15786844 0.24538881 0.30986908],L(w) = 53.23139732983651
Iterations 3: w = [0.09202279 0.17614805 0.20867307 0.32373998 0.40881505],L(w) = 51.08298302832588
Iterations 4: w = [0.11371115 0.21774302 0.25859387 0.40042971 0.50566573],L(w) = 49.023328643609815
Iterations 5: w = [0.13489665 0.25840473 0.30764564 0.4754935  0.60046563],L(w) = 47.048751371204844
Iterations 6: w = [0.15559084 0.29815414 0.35584294 0.54896606 0.69325828],L(w) = 45.1557218697179
Iterations 7: w = [0.175805   0.3370117  0.40320011 0.62088138 0.78408629],L(w) = 43.34085783871291
Iterations 8: w = [0.19555018 0.37499743 0.44973127 0.69127271 0.87299137],L(w) = 41.60091786646066
Iterations 9: w = [0.21483716 0.41213088 0.49545029 0.76017257 0.96001433],L(w) = 39.932795536186354


In [5]:
def sloss(w,i):
    x,y = points[i]
    return (w.dot(x)-y)**2

def sDloss(w,i):
    x,y = points[i]
    return (2*(w.dot(x)-y)*x)

def sGradientDescent(sloss,sDloss,D,numPoints):
    w = np.zeros(D)
    numUpdates = 1
    for t in range(1000):
        for i in range (numPoints):
            
            loss = sloss(w,i)
            gradient = sDloss(w,i)
            numUpdates +=1
            lr = 1/numUpdates
            w = w - lr*gradient
        print(f'Iterations {t}: w = {w},L(w) = {loss}')

sGradientDescent(sloss,sDloss,D,len(points))


    

Iterations 0: w = [0.98842135 1.99845298 3.00021745 4.00055932 5.00169762],L(w) = 0.5054813104275734
Iterations 1: w = [0.99058783 1.99880392 3.0009113  4.00094375 5.00162768],L(w) = 0.505720388628243
Iterations 2: w = [0.99131141 1.99891856 3.00114113 4.00107587 5.00160588],L(w) = 0.5058092410483397
Iterations 3: w = [0.99167353 1.99897539 3.00125576 4.00114286 5.0015953 ],L(w) = 0.5058556622223582
Iterations 4: w = [0.99189092 1.99900931 3.00132444 4.0011834  5.00158907],L(w) = 0.5058842073983671
Iterations 5: w = [0.9920359  1.99903186 3.00137019 4.00121058 5.00158496],L(w) = 0.5059035424193006
Iterations 6: w = [0.99213949 1.99904792 3.00140284 4.00123007 5.00158205],L(w) = 0.5059175088046199
Iterations 7: w = [0.99221719 1.99905995 3.00142732 4.00124473 5.00157989],L(w) = 0.5059280715679997
Iterations 8: w = [0.99227764 1.99906929 3.00144636 4.00125616 5.00157821],L(w) = 0.5059363406215883
Iterations 9: w = [0.992326   1.99907675 3.00146158 4.00126533 5.00157688],L(w) = 0.50594299